-- Populate sort_order for all checklist_items based on the specified order
-- Create a mapping of item names to their sort order
WITH item_order AS (
  SELECT name, row_number() OVER (ORDER BY idx) - 1 as sort_order
  FROM (VALUES
    (1, 'Order the plans from Architect'),
    (2, 'Retire Gas (add w.o) to existing house'),
    (3, 'Retire Water to existing house (paid)'),
    (4, 'Retire Electric (add w.o)'),
    (5, 'Protect Right a Way Tree - Bham'),
    (6, 'Apply for Sewer Cap Permit'),
    (7, 'Apply and pay for Water stop box'),
    (8, 'Pay for new water service'),
    (9, 'Apply for Gas Permit'),
    (10, 'Install temp electric on pole'),
    (11, 'Apply for Construction Fence Permit'),
    (12, 'Fence Insp. Ch on swing of gate'),
    (13, 'Letter of Intent - Bham'),
    (14, 'Demo Permit'),
    (15, 'Asbestos Survey'),
    (16, 'Asbestos Removal (if applicable)'),
    (17, 'Put Dust Sign on Fence (RO)'),
    (18, 'Put Address on Fence'),
    (19, 'Pest Review & Submit Letter (RO)'),
    (20, 'Birmingham Neighbor Letter'),
    (21, 'Add in attic insulation after drywall'),
    (22, 'Insulation Certificate (Bham)'),
    (23, 'Take out building permit'),
    (24, 'Install Temp Fence'),
    (25, 'Install Soil Erosion/Silt Fence'),
    (26, 'Order Port a potty'),
    (27, 'Receive Clearance for Electric for Demo'),
    (28, 'Receive Clearance for Gas for Demo'),
    (29, 'Receive Building Permit'),
    (30, 'Survey Lot'),
    (31, 'Send Build. Survey & Lot Survey to City'),
    (32, 'Demo House'),
    (33, 'Excavate'),
    (34, 'Open hole inspection (Bham) after house is demo'),
    (35, 'Scope Sewer'),
    (36, 'Put Footing In'),
    (37, 'Pin Footing'),
    (38, 'Footing Inspection'),
    (39, 'Put Rod in Basement'),
    (40, 'Pour Basement Walls'),
    (41, 'Brace Basement Walls'),
    (42, 'Final Electrical Meter Box (walls have to be up)'),
    (43, 'Basement Inspection'),
    (44, 'Backfill'),
    (45, 'Clear path for gasline (take pic facing street)'),
    (46, 'Order 1x3 for driveway'),
    (47, 'Backfill Inspection'),
    (48, 'Trench Garage'),
    (49, 'Make Sure Porch is 4'' Higher'),
    (50, 'Order Steel'),
    (51, 'Rough Carpentry'),
    (52, 'Get Basement Ready for Plumbing'),
    (53, 'Order Peastone'),
    (54, 'Call Inspection for Plumbing'),
    (55, 'Call Inspection for Peagravel'),
    (56, 'Order Trusses'),
    (57, 'Order Shingles'),
    (58, 'Call rough heater for roof penetration (24h before shingles install)'),
    (59, 'Order Windows'),
    (60, 'Order Front, Side Doors'),
    (61, 'Order Siding'),
    (62, 'Order Rough Plumbing Material'),
    (63, 'Sil Plate Inspection'),
    (64, 'Frame'),
    (65, 'Install Mechanical'),
    (66, 'Mechanical Inspection'),
    (67, 'Rough Heat Fireplace'),
    (68, 'Heat Inspection'),
    (69, 'Fireplace Inspection'),
    (70, 'Rough Plumbing'),
    (71, 'Rough Plumbing Inspection'),
    (72, 'Rough Electrical'),
    (73, 'Rough Electrical Inspection'),
    (74, 'Remove Temp Electrical'),
    (75, 'Order Rough Building Lumber'),
    (76, 'Get Truss and Window Specs'),
    (77, 'Rough Building'),
    (78, 'Install Siding'),
    (79, 'Installed Stop Box'),
    (80, 'Order Cabinets'),
    (81, 'Rough Building Inspection'),
    (82, 'Paint Exterior'),
    (83, 'Gutters'),
    (84, 'Open Ceiling Inspection (Porch)'),
    (85, 'Order Garage Doors'),
    (86, 'Pour Basement Floors'),
    (87, 'Come Back and Rough Basement'),
    (88, 'Rough Elec Upstairs/Basement'),
    (89, 'Rough Heat Upstairs/Basement'),
    (90, 'Rough Plumbing Upstairs/Basement'),
    (91, 'Rough Fireplace'),
    (92, 'Insulate'),
    (93, 'Measure Finish Lumber'),
    (94, 'Permanent Electric'),
    (95, 'Insulate Inspection'),
    (96, 'Drywall'),
    (97, 'Order Fixtures'),
    (98, 'Order Exterior Stone'),
    (99, 'Ductwork'),
    (100, 'Measure/Order Trim'),
    (101, 'Order Appliances'),
    (102, 'Order Carpet'),
    (103, 'Order Wood Floor Material'),
    (104, 'Prime Interior'),
    (105, 'Receive Cabinets'),
    (106, 'Install Cabinets'),
    (107, 'Measure/Order Quartz'),
    (108, 'Spot the House'),
    (109, 'Install Stone'),
    (110, 'Wall Registers'),
    (111, 'Measure/Order Ceramic Material'),
    (112, 'Install Ceramic'),
    (113, 'Order Shower Door'),
    (114, 'Caulk'),
    (115, 'Grade Exterior'),
    (116, 'Paint Interior'),
    (117, 'Order Cabinet Knobs'),
    (118, 'Order Door Knobs'),
    (119, 'Order Exterior Cement'),
    (120, 'Install Carpet'),
    (121, 'Install Wood Floor'),
    (122, 'Screw Floors'),
    (123, 'Install Shower Door'),
    (124, 'Final Grade'),
    (125, 'Install Appliances'),
    (126, 'Install Sprinkler'),
    (127, 'Grass'),
    (128, 'Install Screens'),
    (129, 'Order Street Tree - RO'),
    (130, 'Blower Door Test'),
    (131, 'Final Electric'),
    (132, 'Final Heat'),
    (133, 'Final Plumbing'),
    (134, 'Final Mechanical/Fireplace'),
    (135, 'Survey As built'),
    (136, 'Final Building Inspection'),
    (137, 'Clean windows')
  ) AS t(idx, name)
)
UPDATE checklist_items
SET sort_order = item_order.sort_order
FROM item_order
WHERE checklist_items.name = item_order.name;

-- Also populate sort_order in checklist_checks based on the item's sort_order
UPDATE checklist_checks
SET sort_order = (
  SELECT ci.sort_order
  FROM checklist_items ci
  WHERE ci.id = checklist_checks.item_id
)
WHERE sort_order = 0;
